apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api
  namespace: acdp
  labels:
    app: platform-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-api
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      containers:
        - name: platform-api
          image: 243333338815.dkr.ecr.us-west-2.amazonaws.com/aws-container-delivery-platform-api:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAME
              value: platform-api
            - name: APP_VERSION
              value: v1.0.0
            - name: APP_ENV
              value: eks
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"